### PR TITLE
v1.3.0

### PR DESCRIPTION
**Pull request by dr-dimitru**
- Compatibility with latest meteor
 - No more CoffeeScript
 - Codebase review + listing with meteor guidelines
 - Move everything to ES6, support for `import` statement
 - Other enhancements and improvements

### CODE REVIEW

**Comment by dr-dimitru** [comment]
Hi @jazeee ,

I put some of my background work around phantomjs and meteor eco-system into this PR.
As you may see `examples` is removed from this PR. Turned out everything inside package directory is published to atmosphere, and every developer used this package downloads `examples` folder. Moreover `examples` will be build-in into theirs production apps.

I'm suggesting to create separate repository for examples, or even deprecate it.

Let me know what do you think, and if it looks good to you, merge and `meteor publish`

**Comment by dr-dimitru** [comment]
Hi @jazeee ,

Any news on this one?

**Comment by jazeee** [comment]
Hi there, I am in the middle of moving across the US, and new job.
I don't know how much I can help here. Ideally, we can transfer this to @dr-dimitru for ownership.
The Meteor package would be better owned by you too, but I haven't had time to look at how to do that.
If you have some info on this, I can look at doing the transfer.
Sorry about that.

**Comment by jazeee** [comment]
Let me know and I'll go ahead and merge, but I haven't really reviewed the changes. I'll have to assume that @dr-dimitru is comfortable with the changes.
I'll then publish to Meteor to at least get it out there.

It couldn't hurt to have someone else review it if possible. I just am too overloaded...

**Comment by dr-dimitru** [comment]
Hi @jazeee ,

Congrats on new position.
Sure it's ready to be merged and published.

+1 for transferring package ownership to me.
You can try to add me as maintainer, some info here - http://stackoverflow.com/questions/29267399/how-to-add-collaborator-for-meteor-package-in-atmosphere

**Comment by jazeee** [comment]
What is your Meteor Id?

**Comment by jazeee** [comment]
I've created cachedspiderable organization.
I believe I have added you (drdimitru)

Now, need to transfer the package into that.

**Comment by dr-dimitru** [comment]
Yes, I was added to cachedspiderable.

But package still published under your name. So, I believe it's better to add me as collaborator to existing package, otherwise we have to re-publish it under new name, which will be: `cachedspiderable:spiderable-longer-timeout`

**Comment by jazeee** [comment]
Ahh, yes, that is what I needed to do.
You are now a maintainer.

**Comment by jazeee** [comment]
Feel free to take over. @drdimitru You are probably the best
maintainer/owner for this project now.
Thanks for everything.
Jaz.

**Comment by dr-dimitru** [comment]
Thank you Jaz

**Pull request merged**
